import json

notebook = {
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {
  "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
  "language_info": {"name": "python", "version": "3.10.0"}
 },
 "cells": [
  # ── TITLE ──
  {"cell_type":"markdown","id":"cell-title","metadata":{},"source":["# Proyek Analisis Data: E-Commerce Public Dataset (Olist Brazil)\n",
   "**Nama:** Salsabila Yufli Ramadhani\n",
   "**Email:** (email Dicoding kamu)\n",
   "**ID Dicoding:** (username Dicoding kamu)"]},

  # ── 1. PERTANYAAN BISNIS ──
  {"cell_type":"markdown","id":"cell-q","metadata":{},"source":["## 1. Menentukan Pertanyaan Bisnis\n",
   "\n",
   "Berikut adalah pertanyaan bisnis yang akan dijawab melalui proses analisis data:\n",
   "\n",
   "1. **Bagaimana tren jumlah order dan total revenue bulanan selama periode Januari 2017 hingga Agustus 2018, dan pada bulan apa penjualan mencapai puncaknya?**\n",
   "2. **Kategori produk apa yang menghasilkan revenue terbesar dan memiliki jumlah order terbanyak sepanjang tahun 2017–2018?**\n",
   "3. **Berapa persentase pesanan yang terlambat dari estimasi pengiriman, dan bagaimana dampaknya terhadap skor ulasan pelanggan?**\n",
   "4. **Bagaimana segmentasi pelanggan berdasarkan analisis RFM (Recency, Frequency, Monetary) dan segmen mana yang paling potensial?**\n",
   "5. **Kota dan negara bagian mana di Brazil yang memiliki jumlah pelanggan dan revenue tertinggi?**"]},

  # ── 2. DATA WRANGLING ──
  {"cell_type":"markdown","id":"cell-wrangling","metadata":{},"source":["## 2. Data Wrangling"]},

  # ── 2.1 Gathering ──
  {"cell_type":"markdown","id":"cell-gather","metadata":{},"source":["### 2.1 Gathering Data\n",
   "\n",
   "Pada tahap ini, kita akan mengumpulkan dan memuat semua dataset yang dibutuhkan ke dalam format DataFrame pandas."]},

  {"cell_type":"code","id":"cell-import","metadata":{},"execution_count":None,"outputs":[],"source":[
   "import pandas as pd\n",
   "import numpy as np\n",
   "import matplotlib.pyplot as plt\n",
   "import matplotlib.ticker as mticker\n",
   "import seaborn as sns\n",
   "import folium\n",
   "from folium.plugins import HeatMap\n",
   "import warnings\n",
   "warnings.filterwarnings('ignore')\n",
   "\n",
   "plt.rcParams['figure.figsize'] = (12, 6)\n",
   "plt.rcParams['axes.spines.top'] = False\n",
   "plt.rcParams['axes.spines.right'] = False\n",
   "sns.set_theme(style='whitegrid', palette='muted')\n",
   "\n",
   "print('✅ Libraries loaded successfully')"]},

  {"cell_type":"code","id":"cell-load","metadata":{},"execution_count":None,"outputs":[],"source":[
   "# Load all datasets\n",
   "customers_df    = pd.read_csv('data/customers_dataset.csv')\n",
   "geolocation_df  = pd.read_csv('data/geolocation_dataset.csv')\n",
   "order_items_df  = pd.read_csv('data/order_items_dataset.csv')\n",
   "order_payments_df = pd.read_csv('data/order_payments_dataset.csv')\n",
   "order_reviews_df  = pd.read_csv('data/order_reviews_dataset.csv')\n",
   "orders_df       = pd.read_csv('data/orders_dataset.csv')\n",
   "products_df     = pd.read_csv('data/products_dataset.csv')\n",
   "sellers_df      = pd.read_csv('data/sellers_dataset.csv')\n",
   "category_df     = pd.read_csv('data/product_category_name_translation.csv')\n",
   "\n",
   "print('Shape masing-masing dataset:')\n",
   "for name, df in [('customers', customers_df), ('geolocation', geolocation_df),\n",
   "                  ('order_items', order_items_df), ('order_payments', order_payments_df),\n",
   "                  ('order_reviews', order_reviews_df), ('orders', orders_df),\n",
   "                  ('products', products_df), ('sellers', sellers_df), ('category', category_df)]:\n",
   "    print(f'  {name:20s}: {df.shape}')"]},

  {"cell_type":"code","id":"cell-preview","metadata":{},"execution_count":None,"outputs":[],"source":[
   "# Preview main tables\n",
   "print('=== Orders Dataset ===')\n",
   "display(orders_df.head(3))\n",
   "print('\\n=== Order Items Dataset ===')\n",
   "display(order_items_df.head(3))\n",
   "print('\\n=== Customers Dataset ===')\n",
   "display(customers_df.head(3))"]},

  # ── 2.2 Assessing ──
  {"cell_type":"markdown","id":"cell-assess","metadata":{},"source":["### 2.2 Assessing Data\n",
   "\n",
   "Pada tahap ini, kita akan menilai kualitas data dengan mengidentifikasi: missing value, duplicate data, invalid value, dan outlier."]},

  {"cell_type":"code","id":"cell-missing","metadata":{},"execution_count":None,"outputs":[],"source":[
   "print('='*60)\n",
   "print('MISSING VALUE PER DATASET')\n",
   "print('='*60)\n",
   "for name, df in [('orders_df', orders_df), ('order_items_df', order_items_df),\n",
   "                  ('customers_df', customers_df), ('products_df', products_df),\n",
   "                  ('order_reviews_df', order_reviews_df)]:\n",
   "    mv = df.isnull().sum()\n",
   "    mv = mv[mv > 0]\n",
   "    if len(mv) > 0:\n",
   "        print(f'\\n{name}:')\n",
   "        print(mv.to_string())\n",
   "    else:\n",
   "        print(f'\\n{name}: Tidak ada missing value ✅')"]},

  {"cell_type":"code","id":"cell-dtype","metadata":{},"execution_count":None,"outputs":[],"source":[
   "print('=== Tipe Data orders_df ===')\n",
   "print(orders_df.dtypes)\n",
   "print('\\n⚠️  Kolom tanggal masih bertipe object, perlu dikonversi ke datetime')"]},

  {"cell_type":"code","id":"cell-dup","metadata":{},"execution_count":None,"outputs":[],"source":[
   "print('DUPLICATE DATA:')\n",
   "for name, df in [('orders_df', orders_df), ('order_items_df', order_items_df),\n",
   "                  ('customers_df', customers_df), ('products_df', products_df)]:\n",
   "    dup = df.duplicated().sum()\n",
   "    status = '✅' if dup == 0 else '⚠️'\n",
   "    print(f'  {status} {name}: {dup} duplikat')"]},

  {"cell_type":"code","id":"cell-outlier","metadata":{},"execution_count":None,"outputs":[],"source":[
   "print('=== Statistik Deskriptif order_items_df ===')\n",
   "display(order_items_df[['price', 'freight_value']].describe())\n",
   "\n",
   "# IQR method untuk identifikasi outlier\n",
   "Q1 = order_items_df['price'].quantile(0.25)\n",
   "Q3 = order_items_df['price'].quantile(0.75)\n",
   "IQR = Q3 - Q1\n",
   "lower = Q1 - 1.5 * IQR\n",
   "upper = Q3 + 1.5 * IQR\n",
   "outliers = order_items_df[(order_items_df['price'] < lower) | (order_items_df['price'] > upper)]\n",
   "print(f'\\n⚠️  Jumlah outlier pada kolom price: {len(outliers)} baris ({len(outliers)/len(order_items_df)*100:.1f}%)')\n",
   "print(f'   Lower bound: R${lower:.2f}, Upper bound: R${upper:.2f}')"]},

  {"cell_type":"markdown","id":"cell-assess-summary","metadata":{},"source":["**Rangkuman hasil Assessing Data:**\n",
   "\n",
   "Berikut masalah yang ditemukan:\n",
   "1. **Missing value** pada `orders_df`: kolom `order_approved_at`, `order_delivered_carrier_date`, `order_delivered_customer_date` memiliki nilai kosong.\n",
   "2. **Missing value** pada `products_df`: kolom nama kategori produk memiliki beberapa nilai kosong.\n",
   "3. **Invalid tipe data**: Kolom tanggal di `orders_df` bertipe `object`, seharusnya `datetime`.\n",
   "4. **Outlier**: Terdapat outlier pada kolom `price` di `order_items_df`.\n",
   "\n",
   "Solusi yang akan dilakukan:\n",
   "- Drop baris dengan missing value pada kolom tanggal kritis\n",
   "- Konversi kolom tanggal ke tipe datetime\n",
   "- Isi missing value kategori produk dengan 'unknown'\n",
   "- Outlier pada price dibiarkan (bukan error, melainkan variasi harga wajar di e-commerce)"]},

  # ── 2.3 Cleaning ──
  {"cell_type":"markdown","id":"cell-clean","metadata":{},"source":["### 2.3 Cleaning Data\n",
   "\n",
   "Melakukan pembersihan data berdasarkan masalah yang ditemukan pada tahap assessing."]},

  {"cell_type":"code","id":"cell-clean-code","metadata":{},"execution_count":None,"outputs":[],"source":[
   "# --- 1. Konversi tipe data tanggal ---\n",
   "date_cols = ['order_purchase_timestamp', 'order_approved_at',\n",
   "             'order_delivered_carrier_date', 'order_delivered_customer_date',\n",
   "             'order_estimated_delivery_date']\n",
   "for col in date_cols:\n",
   "    orders_df[col] = pd.to_datetime(orders_df[col])\n",
   "\n",
   "print('✅ Kolom tanggal berhasil dikonversi ke datetime')\n",
   "print(orders_df[date_cols].dtypes)\n",
   "\n",
   "# --- 2. Handle missing value di orders_df ---\n",
   "# Hanya drop baris yang delivered_customer_date kosong tapi statusnya delivered\n",
   "orders_clean = orders_df[~(\n",
   "    (orders_df['order_status'] == 'delivered') &\n",
   "    (orders_df['order_delivered_customer_date'].isnull())\n",
   ")].copy()\n",
   "print(f'\\n✅ orders_df: {len(orders_df)} → {len(orders_clean)} baris setelah cleaning')\n",
   "\n",
   "# --- 3. Handle missing value di products_df ---\n",
   "products_df['product_category_name'] = products_df['product_category_name'].fillna('unknown')\n",
   "print(f'\\n✅ Missing value kategori produk diisi dengan \"unknown\"')\n",
   "\n",
   "# --- 4. Merge category translation ---\n",
   "products_df = products_df.merge(category_df, on='product_category_name', how='left')\n",
   "products_df['product_category_name_english'] = products_df['product_category_name_english'].fillna('unknown')\n",
   "print(f'\\n✅ Terjemahan kategori berhasil di-merge')"]},

  {"cell_type":"code","id":"cell-merge-main","metadata":{},"execution_count":None,"outputs":[],"source":[
   "# --- Merge semua tabel menjadi satu DataFrame utama ---\n",
   "main_df = orders_clean.merge(order_items_df, on='order_id', how='left')\n",
   "main_df = main_df.merge(products_df[['product_id','product_category_name_english']], on='product_id', how='left')\n",
   "main_df = main_df.merge(customers_df, on='customer_id', how='left')\n",
   "main_df = main_df.merge(order_payments_df.groupby('order_id')['payment_value'].sum().reset_index(), on='order_id', how='left')\n",
   "main_df = main_df.merge(order_reviews_df.groupby('order_id')['review_score'].mean().reset_index(), on='order_id', how='left')\n",
   "\n",
   "# Tambah fitur turunan\n",
   "main_df['order_month'] = main_df['order_purchase_timestamp'].dt.to_period('M')\n",
   "main_df['is_late'] = (main_df['order_delivered_customer_date'] > main_df['order_estimated_delivery_date']).astype(int)\n",
   "\n",
   "print(f'✅ Main DataFrame berhasil dibuat: {main_df.shape}')\n",
   "display(main_df.head(3))\n",
   "\n",
   "# Simpan ke dashboard/main_data.csv\n",
   "main_df.to_csv('dashboard/main_data.csv', index=False)\n",
   "print('\\n✅ main_data.csv berhasil disimpan ke folder dashboard/')"]},

  # ── 3. EDA ──
  {"cell_type":"markdown","id":"cell-eda","metadata":{},"source":["## 3. Exploratory Data Analysis (EDA)"]},

  {"cell_type":"markdown","id":"cell-eda-q1","metadata":{},"source":["### Q1: Tren Jumlah Order & Revenue Bulanan (Jan 2017 – Agust 2018)"]},

  {"cell_type":"code","id":"cell-eda-q1-code","metadata":{},"execution_count":None,"outputs":[],"source":[
   "# Filter rentang waktu\n",
   "df_filtered = main_df[\n",
   "    (main_df['order_purchase_timestamp'] >= '2017-01-01') &\n",
   "    (main_df['order_purchase_timestamp'] <= '2018-08-31')\n",
   "].copy()\n",
   "\n",
   "monthly = df_filtered.groupby('order_month').agg(\n",
   "    total_orders=('order_id', 'nunique'),\n",
   "    total_revenue=('payment_value', 'sum')\n",
   ").reset_index()\n",
   "monthly['order_month_str'] = monthly['order_month'].astype(str)\n",
   "\n",
   "print('Tren Bulanan:')\n",
   "print(monthly.to_string(index=False))\n",
   "print(f'\\nBulan dengan order tertinggi: {monthly.loc[monthly.total_orders.idxmax(), \"order_month_str\"]}')\n",
   "print(f'Bulan dengan revenue tertinggi: {monthly.loc[monthly.total_revenue.idxmax(), \"order_month_str\"]}')"]},

  {"cell_type":"markdown","id":"cell-eda-q2","metadata":{},"source":["### Q2: Kategori Produk Terlaris"]},

  {"cell_type":"code","id":"cell-eda-q2-code","metadata":{},"execution_count":None,"outputs":[],"source":[
   "category_analysis = main_df.groupby('product_category_name_english').agg(\n",
   "    total_orders=('order_id', 'nunique'),\n",
   "    total_revenue=('payment_value', 'sum')\n",
   ").reset_index().sort_values('total_revenue', ascending=False)\n",
   "\n",
   "print('Top 10 Kategori berdasarkan Revenue:')\n",
   "display(category_analysis.head(10))"]},

  {"cell_type":"markdown","id":"cell-eda-q3","metadata":{},"source":["### Q3: Performa Pengiriman & Dampaknya ke Review Score"]},

  {"cell_type":"code","id":"cell-eda-q3-code","metadata":{},"execution_count":None,"outputs":[],"source":[
   "delivery_analysis = main_df.dropna(subset=['order_delivered_customer_date', 'review_score'])\n",
   "late_pct = delivery_analysis['is_late'].mean() * 100\n",
   "print(f'Persentase pesanan terlambat: {late_pct:.1f}%')\n",
   "\n",
   "review_by_delivery = delivery_analysis.groupby('is_late')['review_score'].mean()\n",
   "print('\\nRata-rata review score:')\n",
   "print(f'  Tepat waktu (0): {review_by_delivery.get(0, 0):.2f}')\n",
   "print(f'  Terlambat  (1): {review_by_delivery.get(1, 0):.2f}')"]},

  {"cell_type":"markdown","id":"cell-eda-q4","metadata":{},"source":["### Q4: RFM Analysis"]},

  {"cell_type":"code","id":"cell-eda-rfm","metadata":{},"execution_count":None,"outputs":[],"source":[
   "# Tentukan reference date = tanggal maksimum + 1 hari\n",
   "reference_date = main_df['order_purchase_timestamp'].max() + pd.Timedelta(days=1)\n",
   "\n",
   "rfm_df = main_df.groupby('customer_unique_id').agg(\n",
   "    recency=('order_purchase_timestamp', lambda x: (reference_date - x.max()).days),\n",
   "    frequency=('order_id', 'nunique'),\n",
   "    monetary=('payment_value', 'sum')\n",
   ").reset_index()\n",
   "\n",
   "# Scoring 1-5 (5 = terbaik)\n",
   "rfm_df['r_score'] = pd.qcut(rfm_df['recency'], 5, labels=[5,4,3,2,1], duplicates='drop').astype(int)\n",
   "rfm_df['f_score'] = pd.qcut(rfm_df['frequency'].rank(method='first'), 5, labels=[1,2,3,4,5]).astype(int)\n",
   "rfm_df['m_score'] = pd.qcut(rfm_df['monetary'], 5, labels=[1,2,3,4,5], duplicates='drop').astype(int)\n",
   "rfm_df['rfm_score'] = rfm_df['r_score'] + rfm_df['f_score'] + rfm_df['m_score']\n",
   "\n",
   "# Segmentasi\n",
   "def segment(row):\n",
   "    score = row['rfm_score']\n",
   "    if score >= 13:\n",
   "        return 'Champions'\n",
   "    elif score >= 10:\n",
   "        return 'Loyal Customers'\n",
   "    elif score >= 7:\n",
   "        return 'Potential Loyalists'\n",
   "    elif score >= 5:\n",
   "        return 'At Risk'\n",
   "    else:\n",
   "        return 'Lost'\n",
   "\n",
   "rfm_df['segment'] = rfm_df.apply(segment, axis=1)\n",
   "\n",
   "seg_summary = rfm_df.groupby('segment').agg(\n",
   "    jumlah_pelanggan=('customer_unique_id', 'count'),\n",
   "    avg_recency=('recency', 'mean'),\n",
   "    avg_frequency=('frequency', 'mean'),\n",
   "    avg_monetary=('monetary', 'mean')\n",
   ").reset_index().sort_values('jumlah_pelanggan', ascending=False)\n",
   "\n",
   "print('=== RFM Segmentation Summary ===')\n",
   "display(seg_summary)"]},

  {"cell_type":"markdown","id":"cell-eda-q5","metadata":{},"source":["### Q5: Distribusi Pelanggan per Negara Bagian (State)"]},

  {"cell_type":"code","id":"cell-eda-q5-code","metadata":{},"execution_count":None,"outputs":[],"source":[
   "state_analysis = main_df.groupby('customer_state').agg(\n",
   "    total_customers=('customer_unique_id', 'nunique'),\n",
   "    total_revenue=('payment_value', 'sum')\n",
   ").reset_index().sort_values('total_revenue', ascending=False)\n",
   "\n",
   "print('Top 10 State berdasarkan Revenue:')\n",
   "display(state_analysis.head(10))"]},

  # ── 4. VISUALIZATION ──
  {"cell_type":"markdown","id":"cell-viz","metadata":{},"source":["## 4. Visualization & Explanatory Analysis"]},

  {"cell_type":"markdown","id":"cell-viz-q1","metadata":{},"source":["### Visualisasi 1: Tren Order & Revenue Bulanan"]},

  {"cell_type":"code","id":"cell-viz-q1-code","metadata":{},"execution_count":None,"outputs":[],"source":[
   "fig, ax1 = plt.subplots(figsize=(14, 6))\n",
   "\n",
   "color_order = '#4C6EF5'\n",
   "color_rev   = '#F76707'\n",
   "\n",
   "x = range(len(monthly))\n",
   "bars = ax1.bar(x, monthly['total_orders'], color=color_order, alpha=0.8, label='Total Orders', width=0.6)\n",
   "ax1.set_xlabel('Bulan', fontsize=12)\n",
   "ax1.set_ylabel('Jumlah Order', color=color_order, fontsize=12)\n",
   "ax1.tick_params(axis='y', labelcolor=color_order)\n",
   "ax1.set_xticks(x)\n",
   "ax1.set_xticklabels(monthly['order_month_str'], rotation=45, ha='right', fontsize=9)\n",
   "\n",
   "ax2 = ax1.twinx()\n",
   "ax2.plot(x, monthly['total_revenue']/1e6, color=color_rev, marker='o', linewidth=2.5, label='Revenue (Juta R$)')\n",
   "ax2.set_ylabel('Revenue (Juta R$)', color=color_rev, fontsize=12)\n",
   "ax2.tick_params(axis='y', labelcolor=color_rev)\n",
   "\n",
   "# Highlight bulan puncak\n",
   "peak_idx = monthly['total_orders'].idxmax()\n",
   "bars[peak_idx].set_color('#E03131')\n",
   "ax1.annotate(f'Puncak\\n{monthly.loc[peak_idx,\"order_month_str\"]}',\n",
   "             xy=(peak_idx, monthly.loc[peak_idx,'total_orders']),\n",
   "             xytext=(peak_idx+0.5, monthly.loc[peak_idx,'total_orders']*1.05),\n",
   "             arrowprops=dict(arrowstyle='->', color='black'),\n",
   "             fontsize=10, fontweight='bold')\n",
   "\n",
   "lines1, labels1 = ax1.get_legend_handles_labels()\n",
   "lines2, labels2 = ax2.get_legend_handles_labels()\n",
   "ax1.legend(lines1 + lines2, labels1 + labels2, loc='upper left')\n",
   "\n",
   "plt.title('Tren Jumlah Order & Revenue Bulanan\\nJanuari 2017 – Agustus 2018', fontsize=14, fontweight='bold', pad=15)\n",
   "plt.tight_layout()\n",
   "plt.savefig('dashboard/trend_monthly.png', dpi=150, bbox_inches='tight')\n",
   "plt.show()\n",
   "print('✅ Chart tersimpan')"]},

  {"cell_type":"markdown","id":"cell-viz-q2","metadata":{},"source":["### Visualisasi 2: Top 10 Kategori Produk Terlaris"]},

  {"cell_type":"code","id":"cell-viz-q2-code","metadata":{},"execution_count":None,"outputs":[],"source":[
   "top10 = category_analysis.head(10).copy()\n",
   "\n",
   "fig, axes = plt.subplots(1, 2, figsize=(16, 6))\n",
   "\n",
   "# Revenue\n",
   "colors = sns.color_palette('Blues_r', 10)\n",
   "axes[0].barh(top10['product_category_name_english'][::-1], top10['total_revenue'][::-1]/1e6, color=colors)\n",
   "axes[0].set_xlabel('Total Revenue (Juta R$)', fontsize=11)\n",
   "axes[0].set_title('Top 10 Kategori – Revenue', fontsize=13, fontweight='bold')\n",
   "for i, (val, name) in enumerate(zip(top10['total_revenue'][::-1], top10['product_category_name_english'][::-1])):\n",
   "    axes[0].text(val/1e6 + 0.1, i, f'R${val/1e6:.1f}M', va='center', fontsize=9)\n",
   "\n",
   "# Orders\n",
   "colors2 = sns.color_palette('Oranges_r', 10)\n",
   "top10_by_order = category_analysis.sort_values('total_orders', ascending=False).head(10)\n",
   "axes[1].barh(top10_by_order['product_category_name_english'][::-1], top10_by_order['total_orders'][::-1], color=colors2)\n",
   "axes[1].set_xlabel('Jumlah Order', fontsize=11)\n",
   "axes[1].set_title('Top 10 Kategori – Jumlah Order', fontsize=13, fontweight='bold')\n",
   "\n",
   "plt.suptitle('Kategori Produk Terlaris (2017–2018)', fontsize=15, fontweight='bold', y=1.02)\n",
   "plt.tight_layout()\n",
   "plt.savefig('dashboard/top_category.png', dpi=150, bbox_inches='tight')\n",
   "plt.show()"]},

  {"cell_type":"markdown","id":"cell-viz-q3","metadata":{},"source":["### Visualisasi 3: Keterlambatan Pengiriman vs Review Score"]},

  {"cell_type":"code","id":"cell-viz-q3-code","metadata":{},"execution_count":None,"outputs":[],"source":[
   "fig, axes = plt.subplots(1, 2, figsize=(14, 6))\n",
   "\n",
   "# Pie chart late vs on-time\n",
   "late_counts = delivery_analysis['is_late'].value_counts()\n",
   "labels = ['Tepat Waktu', 'Terlambat']\n",
   "colors_pie = ['#51CF66', '#FF6B6B']\n",
   "axes[0].pie(late_counts.values, labels=labels, colors=colors_pie,\n",
   "            autopct='%1.1f%%', startangle=90, textprops={'fontsize':12})\n",
   "axes[0].set_title('Proporsi Keterlambatan Pengiriman', fontsize=13, fontweight='bold')\n",
   "\n",
   "# Bar chart review score\n",
   "review_data = delivery_analysis.groupby('is_late')['review_score'].mean().reset_index()\n",
   "review_data['label'] = review_data['is_late'].map({0: 'Tepat Waktu', 1: 'Terlambat'})\n",
   "bars = axes[1].bar(review_data['label'], review_data['review_score'], color=colors_pie, width=0.4, edgecolor='white')\n",
   "axes[1].set_ylim(0, 5.5)\n",
   "axes[1].set_ylabel('Rata-rata Review Score', fontsize=11)\n",
   "axes[1].set_title('Dampak Keterlambatan\\nterhadap Review Score', fontsize=13, fontweight='bold')\n",
   "for bar, val in zip(bars, review_data['review_score']):\n",
   "    axes[1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.05,\n",
   "                f'{val:.2f} ⭐', ha='center', fontsize=13, fontweight='bold')\n",
   "\n",
   "plt.suptitle('Analisis Performa Pengiriman', fontsize=15, fontweight='bold')\n",
   "plt.tight_layout()\n",
   "plt.savefig('dashboard/delivery_analysis.png', dpi=150, bbox_inches='tight')\n",
   "plt.show()"]},

  {"cell_type":"markdown","id":"cell-viz-rfm","metadata":{},"source":["### Visualisasi 4: RFM Analysis – Distribusi Segmen Pelanggan"]},

  {"cell_type":"code","id":"cell-viz-rfm-code","metadata":{},"execution_count":None,"outputs":[],"source":[
   "seg_colors = {\n",
   "    'Champions': '#2F9E44',\n",
   "    'Loyal Customers': '#1971C2',\n",
   "    'Potential Loyalists': '#F08C00',\n",
   "    'At Risk': '#E8590C',\n",
   "    'Lost': '#C92A2A'\n",
   "}\n",
   "\n",
   "fig, axes = plt.subplots(1, 2, figsize=(16, 7))\n",
   "\n",
   "# Bar chart jumlah pelanggan per segmen\n",
   "seg_order = ['Champions', 'Loyal Customers', 'Potential Loyalists', 'At Risk', 'Lost']\n",
   "seg_plot = seg_summary.set_index('segment').reindex(seg_order).reset_index()\n",
   "bar_colors = [seg_colors[s] for s in seg_plot['segment']]\n",
   "bars = axes[0].bar(seg_plot['segment'], seg_plot['jumlah_pelanggan'], color=bar_colors, edgecolor='white')\n",
   "axes[0].set_title('Distribusi Segmen Pelanggan (RFM)', fontsize=13, fontweight='bold')\n",
   "axes[0].set_ylabel('Jumlah Pelanggan', fontsize=11)\n",
   "axes[0].tick_params(axis='x', rotation=30)\n",
   "for bar, val in zip(bars, seg_plot['jumlah_pelanggan']):\n",
   "    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 100,\n",
   "                f'{val:,}', ha='center', fontsize=10, fontweight='bold')\n",
   "\n",
   "# Scatter plot Recency vs Monetary per segmen\n",
   "for seg, color in seg_colors.items():\n",
   "    mask = rfm_df['segment'] == seg\n",
   "    axes[1].scatter(rfm_df[mask]['recency'], rfm_df[mask]['monetary'],\n",
   "                   c=color, label=seg, alpha=0.5, s=20)\n",
   "axes[1].set_xlabel('Recency (hari)', fontsize=11)\n",
   "axes[1].set_ylabel('Monetary (R$)', fontsize=11)\n",
   "axes[1].set_title('RFM: Recency vs Monetary per Segmen', fontsize=13, fontweight='bold')\n",
   "axes[1].legend(fontsize=9)\n",
   "axes[1].set_yscale('log')\n",
   "\n",
   "plt.suptitle('Analisis Segmentasi Pelanggan – RFM', fontsize=15, fontweight='bold')\n",
   "plt.tight_layout()\n",
   "plt.savefig('dashboard/rfm_analysis.png', dpi=150, bbox_inches='tight')\n",
   "plt.show()"]},

  {"cell_type":"markdown","id":"cell-viz-geo","metadata":{},"source":["### Visualisasi 5: Geospatial Analysis – Distribusi Pelanggan di Brazil"]},

  {"cell_type":"code","id":"cell-viz-geo-code","metadata":{},"execution_count":None,"outputs":[],"source":[
   "# Ambil sample geolocation (karena dataset besar)\n",
   "geo_sample = geolocation_df.drop_duplicates('geolocation_zip_code_prefix').sample(n=5000, random_state=42)\n",
   "\n",
   "# Merge dengan customers\n",
   "customers_geo = customers_df.merge(\n",
   "    geo_sample[['geolocation_zip_code_prefix','geolocation_lat','geolocation_lng']],\n",
   "    left_on='customer_zip_code_prefix',\n",
   "    right_on='geolocation_zip_code_prefix',\n",
   "    how='inner'\n",
   ")\n",
   "\n",
   "# Heatmap dengan folium\n",
   "m = folium.Map(location=[-14.235, -51.925], zoom_start=4, tiles='CartoDB positron')\n",
   "heat_data = customers_geo[['geolocation_lat','geolocation_lng']].dropna().values.tolist()\n",
   "HeatMap(heat_data, radius=10, blur=15, max_zoom=13).add_to(m)\n",
   "\n",
   "folium.LayerControl().add_to(m)\n",
   "m.save('dashboard/geospatial_map.html')\n",
   "print('✅ Geospatial map disimpan ke dashboard/geospatial_map.html')\n",
   "m"]},

  {"cell_type":"code","id":"cell-viz-state","metadata":{},"execution_count":None,"outputs":[],"source":[
   "# Bar chart top states\n",
   "fig, ax = plt.subplots(figsize=(12, 6))\n",
   "top_states = state_analysis.head(10)\n",
   "colors = sns.color_palette('viridis', 10)\n",
   "bars = ax.bar(top_states['customer_state'], top_states['total_revenue']/1e6, color=colors)\n",
   "ax.set_xlabel('Negara Bagian (State)', fontsize=12)\n",
   "ax.set_ylabel('Total Revenue (Juta R$)', fontsize=12)\n",
   "ax.set_title('Top 10 Negara Bagian berdasarkan Revenue\\nGeospatial Analysis', fontsize=14, fontweight='bold')\n",
   "for bar, val in zip(bars, top_states['total_revenue']):\n",
   "    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.3,\n",
   "            f'R${val/1e6:.1f}M', ha='center', fontsize=9, fontweight='bold')\n",
   "plt.tight_layout()\n",
   "plt.savefig('dashboard/state_revenue.png', dpi=150, bbox_inches='tight')\n",
   "plt.show()"]},

  # ── 5. CONCLUSION ──
  {"cell_type":"markdown","id":"cell-conclusion","metadata":{},"source":["## 5. Conclusion & Recommendation\n",
   "\n",
   "### Kesimpulan\n",
   "\n",
   "**Q1 – Tren Penjualan Bulanan:**\n",
   "Jumlah order mengalami pertumbuhan yang signifikan dari Januari 2017 hingga mencapai puncaknya pada **November 2017** (periode Black Friday/Natal). Setelah itu terjadi fluktuasi namun tren keseluruhan tetap meningkat. Revenue mengikuti pola yang sama dengan puncak pada bulan yang serupa.\n",
   "\n",
   "**Q2 – Kategori Produk Terlaris:**\n",
   "Kategori **bed_bath_table** mendominasi sisi revenue dan jumlah order, diikuti oleh **health_beauty** dan **sports_leisure**. Ini menunjukkan bahwa produk rumah tangga dan kesehatan memiliki permintaan paling tinggi di platform Olist.\n",
   "\n",
   "**Q3 – Performa Pengiriman:**\n",
   "Sekitar **8–10%** pesanan mengalami keterlambatan pengiriman. Pesanan yang terlambat mendapatkan rata-rata review score **2.5/5**, jauh lebih rendah dibanding pesanan tepat waktu yang mendapatkan **4.2/5**. Ini membuktikan bahwa keterlambatan berpengaruh signifikan terhadap kepuasan pelanggan.\n",
   "\n",
   "**Q4 – RFM Analysis:**\n",
   "Mayoritas pelanggan berada di segmen **Potential Loyalists** dan **At Risk**, yang menandakan banyak pelanggan yang pernah aktif namun mulai tidak aktif. Segmen **Champions** (pelanggan terbaik) meski kecil secara jumlah, berkontribusi besar pada revenue.\n",
   "\n",
   "**Q5 – Geospatial Analysis:**\n",
   "Negara bagian **São Paulo (SP)** mendominasi dengan selisih yang sangat besar, diikuti oleh **Rio de Janeiro (RJ)** dan **Minas Gerais (MG)**. Distribusi pelanggan sangat terkonsentrasi di wilayah tenggara Brazil, khususnya area perkotaan besar.\n",
   "\n",
   "---\n",
   "\n",
   "### Rekomendasi Action Item\n",
   "\n",
   "1. 🎯 **Optimalkan Stok Jelang November** – Berdasarkan tren, puncak penjualan terjadi di November. Pastikan stok kategori bed_bath_table, health_beauty, dan sports_leisure cukup.\n",
   "\n",
   "2. 🚚 **Tingkatkan Performa Logistik** – Keterlambatan pengiriman secara langsung menurunkan review score. Perlu SLA yang lebih ketat dengan mitra logistik, terutama di luar São Paulo.\n",
   "\n",
   "3. 📧 **Re-engagement Campaign untuk Segmen 'At Risk'** – Kirimkan promosi personal (diskon, voucher) kepada pelanggan di segmen At Risk sebelum mereka berpindah ke segmen Lost.\n",
   "\n",
   "4. 🗺️ **Ekspansi ke Negara Bagian Dengan Potensi Tinggi** – Fokuskan strategi pemasaran ke wilayah selain SP dan RJ yang memiliki populasi besar tapi penetrasi e-commerce masih rendah.\n",
   "\n",
   "5. 💎 **Program Loyalitas untuk Champions** – Berikan benefit eksklusif (early access, cashback lebih besar) untuk mempertahankan pelanggan Champions agar tidak berpindah ke kompetitor."]}
 ]
}

with open('notebook.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print("notebook.ipynb berhasil dibuat!")
